### ISSUE TITLE
Cannot restore using Google Drive Backup

### ISSUE THREAD

**Issue by s0umitra** [Schwartzblat/WhatsAppPatcher#45]
I am unable to restore from gdrive after Number Verification step, any idea?

Steps-
1) verify number
2) click on "give permisson" (marked 1)
3) Selected my account and pressed "OK"
4) Received the error (marked 2)

![image](https://github.com/Schwartzblat/WhatsAppPatcher/assets/44529322/a20ab7ba-60b0-47df-b6d4-33fc02a80375)

I am using commit- aa90bb5 with WhatsApp version- 2.23.19.78
Tried force-killing the app, cleared cache/storage and reactivated the number, restarted phone, used multiple networks.

**Comment by Schwartzblat** [comment]
I know what the problem is and I will solve it tonight.

**Comment by jeverling** [comment]
Hm no sorry no idea, I restored a local backup so I didn't try that step. It seems a bit unlikely that it has to do with the patched apk when it initializes fine otherwise but who knows. :/

Do you have 2FA enabled in Google?
Could it maybe be one of those things:

- Verify you're attempting to restore data from the same phone number and Google account that the backup was created on.
- Verify there's enough room on your phone to restore the backup.
- Verify you have Google Play services/Google Drive installed on your phone.

**Comment by Schwartzblat** [comment]
Solved, try the new apk.
